version: '3.8'
services:
  spring-app:
    image: lt-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1999:1999"
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ltdb
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-1234}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      
      # Server Configuration
      SERVER_PORT: 1999
      
      # Logging Configuration
      LOGGING_FILE_NAME: ltapp.log
      SPRING_PROFILES_ACTIVE: docker
      
      # Security Configuration
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-default_jwt_secret_key_for_development_only}
      IP_CHECK_SECRET_KEY: ${IP_CHECK_SECRET_KEY:-default_ip_check_secret_for_development_only}
      
      # Swagger Configuration
      SWAGGER_AUTH_USERNAME: ${SWAGGER_USERNAME:-ltuser}
      SWAGGER_AUTH_PASSWORD: ${SWAGGER_PASSWORD:-1234}
    depends_on:
      - mysql-db
    env_file:
      - .env

  mysql-db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: ltdb
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-1234}
      MYSQL_USER: ${DB_USERNAME:-ltuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db-data: