version: '3.8'
services:
  spring-app:
    image: lt-spring-boot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1999:1999"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ltdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 1999
      LOGGING_FILE_NAME: ltapp.log
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: ltdb
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
